-- AlterTable
ALTER TABLE `post` ADD COLUMN `category` ENUM('UNCATEGORIZED', 'ANNOUNCEMENTS', 'HOMEWORK', 'EVENTS', 'DISCUSSION', 'QUESTIONS', 'RESOURCES', 'NEWS') NOT NULL DEFAULT 'UNCATEGORIZED';

-- AlterTable
ALTER TABLE `user` MODIFY `avatar` VARCHAR(191) NOT NULL DEFAULT '';
